### ISSUE TITLE
Missing requirement : packaging

### ISSUE THREAD

**Issue by matthias4217** [inveniosoftware/invenio-cli#393]
Package version (if known): `1.7.1`

## Describe the bug

After having done à `pip install invenio-cli~=1.7.1`, I have tried to generate a lock of a Pipfile using the command `invenio-cli packages lock`.

The `Pipfile` in question is the following :

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
check-manifest = ">=0.25"

[packages]
invenio-app-rdm = {extras = ["opensearch2"], version = "~=12.0.0"}
invenio-in2p3 = {editable = true, path="./site"}

uwsgi = ">=2.0"
uwsgitop = ">=0.11"
uwsgi-tools = ">=1.1.1"

[requires]
python_version = "3.9"

[pipenv]
allow_prereleases = false
```

However, the locking command fails :

```
File "/usr/local/lib/python3.9/site-packages/invenio_cli/helpers/versions.py", line 20, in <module>
    from packaging.requirements import Requirement
ModuleNotFoundError: No module named 'packaging'
```

It looks like [`packaging`](https://pypi.org/project/packaging/) is missing from the  [`invenio-cli` `pyproject.toml`](https://github.com/inveniosoftware/invenio-cli/blob/master/pyproject.toml).

## Expected behavior

I assumed installing `invenio-cli` would be enough to be able to lock my Pipfile.

## Additional context

I can confirm than doing `pip install packaging~=24.2` as a workaround before trying to use the invenio locking command works fine.
